name: encryption_util
description: A Flutter plugin for encryption and decryption using secure elements.
version: 0.0.1
homepage: https://example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: social.julia.encryptionutil
        pluginClass: EncryptionUtilPlugin
      ios:
        pluginClass: EncryptionUtilPlugin
